# We follow the versioning of Cities Skylines
version: 1.1.1.{build}

configuration: Release

assembly_info:
  patch: true

cache:
  - packages -> **\packages.config

before_build:
  - nuget restore

build:
  verbosity: minimal
  publish_nuget: true
