version: 1.2.1.{build}

configuration: Release

assembly_info:
  patch: true

cache:
  - packages -> **\packages.config

before_build:
  - ps: .appveyor\UpdateBuildVersion.ps1
  - nuget restore

build:
  verbosity: minimal
  publish_nuget: true

on_success:
  - ps: .appveyor\PrepareNewBuildVersion.ps1
