version: 1.3.1.{build}

configuration: Release

assembly_info:
  patch: true

cache:
  - packages -> **\packages.config

before_build:
  - ps: .appveyor\UpdateBuildVersion.ps1
  - nuget restore

build:
  verbosity: minimal
  publish_nuget: true

on_success:
  - ps: .appveyor\PrepareNewBuildVersion.ps1

deploy:
- provider: NuGet
  server: https://www.myget.org/F/cities-skylines/api/v2
  api_key:
    secure: 7zMC37Jd02dfifYyUH6pmztHwQhUKOOXzdsRuKDws7LQpcl3TRZvKjlqIrO0q/FH
  skip_symbols: true
  on:
    branch: master
    appveyor_repo_tag: true
